name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install spacy==3.8 ginza==5.2.0 ja-ginza==5.2.0
        python -m spacy download ja_ginza
        pip install -r requirements.txt
        pip install ruff pytest pytest-cov
    - name: Test with pytest
      run: pytest --cov=src --cov-report=xml
