name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run a simple script (placeholder)
      run: echo "Basic setup complete."

    - name: Cache models
      id: cache-models
      uses: actions/cache@v4
      with:
        path: models/
        key: ${{ runner.os }}-models-${{ hashFiles('scripts/download_models.py') }}
        restore-keys: |
          ${{ runner.os }}-models-

    - name: Download models
      if: steps.cache-models.outputs.cache-hit != 'true'
      run: python scripts/download_models.py