name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Cache models
      id: cache-models
      uses: actions/cache@v4
      with:
        path: models/
        key: ${{ runner.os }}-models-${{ hashFiles('scripts/download_models.py') }}
        restore-keys: |
          ${{ runner.os }}-models-

    - name: Download models
      if: steps.cache-models.outputs.cache-hit != 'true'
      run: python scripts/download_models.py

    - name: Build semantic vector database
      run: python src/build_database.py --img_dir sigma_images

    - name: Set up Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        ollama serve & # Run Ollama in background
        sleep 5 # Give Ollama time to start
        ollama pull codegemma:latest

    - name: Verify Ollama setup
      run: ollama list | grep codegemma:latest