name: Python CI

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
      - 'docs/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U ginza
        pip install https://github.com/megagonlabs/ginza/releases/download/v5.2.0/ja_ginza-5.2.0-py3-none-any.whl
        pip install -r requirements.txt
        pip install ruff pytest pytest-cov mypy
    - name: Check GiNZA functionality
      run: python check_ginza.py
    - name: Verify model downloads
      run: python scripts/download_models.py
    - name: Create dummy files for tests
      run: |
        mkdir -p sigma_logs
        touch sigma_logs/personal_memory.jsonl

    - name: Build Knowledge Store
      run: python scripts/build_knowledge_store.py

    - name: Build Vector Database
      run: python -m src.sigmasense.build_database --img_dir sigma_images

    - name: Run Ruff Linter
      run: ruff check .

    - name: Run Mypy Type Checker
      run: mypy src/

    - name: Test with pytest
      run: PYTHONPATH=.:src pytest --cov=src --cov-report=xml